:PROPERTIES:
:ID:       2b3a351a-9dc8-411a-84c9-746f49151541
:ROAM_ALIASES: arithmetic
:mtime:    20240430151711 20240430135334 20240430125306 20240419042730 20240324181240
:ctime:    20240321052210
:END:
#+TITLE: Arithmetic
#+filetags: :mathematics:arithmetic:

Branch of mathematics concerned with operations. Systems can be distinguished by the set of numbers the system deals with.

* [[roam:hyperoperation]]

These are the hyperoperations for our most commonly used form of arithmetic.
however other arithmetics can be constructed in [[roam:abstract algebra]].
Additional properties of each operation can be found on their page.
** n = 0
*** [[roam:successor function][Succession]]
Succession in a unary operator.
$\mathbf{S}(n) = n + 1$

** n = 1

*** roam:Addition
addition is repeated succession.
# I think there's a bit of a disconnect between these two operations.
# A number is repeated succession, an addition is the combination of two numbers.
*** roam:Subtraction
subtraction is the inverse operation of addition.
subtraction also introduces the construction of negative numbers.
** n = 2
*** roam:Multiplication
Multiplication is the next level of arithmetic hyperoperation.
Multiplication is repeated addition.

*** Division
Division is the inverse operation of multiplication.
Division also introduces the construction of rational numbers.

** n = 3

*** roam:Exponentiation
exponentiation is repeated multiplication.

*** roam:Polynomial

***
