:PROPERTIES:
:ID:       e0011bbf-730e-4552-8bc1-6c20b8a60d62
:ROAM_REFS: https://plato.stanford.edu/entries/identity-personal/
:mtime:    20240419042757 20240320183908
:ctime:    20240320183908
:END:
#+title: Personal Identity (Stanford Encyclopedia of Philosophy)
#+filetags: :Personal_Identity:DEPRECATED:

This article avoids using the term self.
* Introduction
Problems of personal identity:
** Who Am I?
   Outside of philosophy Personal Identity refers to properties a person feels sense of attachment or ownership.

** Personhood
   What counts as a person? Do fertilized eggs have personhood? Do digitized brains have personhood?


** Persistence
   What makes a person continue to exist as opposed to stop existing?

** Evidence
   How do we differentiate between who is who?

** Population
   How do we count people?


** What am I?
   What makes us human people? or persons in general. This is different from personhood its trying to account for our material makeup as opposed to our function makeup/

** What concepts truely matter in identity?

* Uses for this reference:
  Integrating the ideas in [[id:e27c7b62-e338-4056-917d-a544725d91aa][PID]].
