:PROPERTIES:
:ID:       845ba2f2-a5b9-4fce-8e8d-842cad9b02e5
:SONG_TITLE: Once in a Lifetime
:ARTIST: Talking Heads
:ALBUM_TYPE: single
:mtime:    20240419042738 20240329223012
:ctime:    20240328144615
:END:
#+title: Once In a Lifetime - Talking Heads - Remain in Light (1980)
#+filetags: :talking_heads:once_in_a_lifetime_talking_heads:bewilderment:confusion:nostalgia:  
* Lyrics
#+begin_quote

*Verse 1*

And you may find yourself living in a shotgun shack

And you may find yourself in another part of the world

And you may find yourself behind the wheel of a large automobile

And you may find yourself in a beautiful house, with a beautiful wife

And you may ask yourself, “Well, how did I get here?”

*Chorus*

Letting the days go by, let the water hold me down

Letting the days go by, water flowing underground

Into the blue again after the money's gone

Once in a lifetime, water flowing underground

*Bridge*

Same as it ever was, same as it ever was

Same as it ever was, same as it ever was

Same as it ever was, same as it ever was

Same as it ever was, same as it ever was

*Verse 3*

Water dissolving and water removing

There is water at the bottom of the ocean

Under the water, carry the water

Remove the water at the bottom of the ocean

Water dissolving and water removing

*Chorus*

Letting the days go by, let the water hold me down

Letting the days go by, water flowing underground

Into the blue again, into the silent water

Under the rocks and stones, there is water underground

Letting the days go by, let the water hold me down

Letting the days go by, water flowing underground

Into the blue again after the money's gone

Once in a lifetime, water flowing underground

*Verse 4*

You may ask yourself, “What is that beautiful house?”

You may ask yourself, “Where does that highway go to?”

And you may ask yourself, “Am I right? Am I wrong?”

And you may say to yourself, “My God! What have I done?”

*Chorus*

Letting the days go by, let the water hold me down

Letting the days go by, water flowing underground

Into the blue again, into the silent water

Under the rocks and stones, there is water underground

Letting the days go by, let the water hold me down

Letting the days go by, water flowing underground

Into the blue again after the money's gone

Once in a lifetime, water flowing underground

*Outro*

Same as it ever was, same as it ever was

Same as it ever was and look where my hand was

Time isn't holding up, time isn't after us

Same as it ever was, same as it ever was

Same as it ever was, same as it ever was

Same as it ever was, same as it ever was

Letting the days go by, same as it ever was

Here a twister comes, here comes the twister

Same as it ever was, same as it ever was (Letting the days go by)

Same as it ever was, same as it ever was (Letting the days go by)

Once in a lifetime (Let the water hold me down)

Letting the days go by (Water flowing underground)

Into the blue again
#+end_quote
* Instrumentation

* Production
** Producer
[[id:17e4cb1f-aa99-4071-947e-519a77e1ae87][Brian Eno]]

* Personal Notes

** Sentiments

This song is about how the singer has let time go by and feels they don't know how they arrived at the point in life they made.
As if they had no control of how their current life went.
