:PROPERTIES:
:ID:       e75c45ff-5744-453b-9ad4-96d3a1335cb0
:mtime:    20240419042800 20240405225222
:ctime:    20240405222729
:END:
#+title: Vampire - Olivia Rodrigo - Guts (2023)
#+filetags: :vampire:olivia_rodrigo:olivia_rodrigo_guts:music:song:  
* Lyrics


** [Verse 1]

#+begin_quote
Hate to give the satisfaction asking how you're doing now

How's the castle built off people you pretend to care about?

Just what you wanted

Look at you, cool guy, you got it

I see the parties and the diamonds sometimes when I close my eyes

Six months of torture you sold as some forbidden paradise

I loved you truly

You gotta laugh at the stupidity
#+end_quote

** [Chorus]

#+begin_quote
'Cause I've made some real big mistakes

But you make the worst one look fine

I should've known it was strange

You only come out at night

I used to think I was smart

But you made me look so naive

The way you sold me for parts

As you sunk your teeth into me, oh

Bloodsucker, fame fucker

Bleedin' me dry like a goddamn vampire
#+end_quote

** [Verse 2]

#+begin_quote
And every girl I ever talked to told me you were bad, bad news

You called them crazy, God, I hate the way I called 'em crazy too

You're so convincing

How do you lie without flinching? (How do you lie? How do you lie? How do you lie?)

Oh, what a mesmerizing, paralyzing, fucked up little thrill

Can't figure out just how you do it and God knows I never will

Went for me and not her

'Cause girls your age know better
#+end_quote

** [Chorus]

#+begin_quote
I've made some real big mistakes

But you make the worst one look fine

I should've known it was strange

You only come out at night

I used to think I was smart

But you made me look so naive

The way you sold me for parts

As you sunk your teeth into me, oh

Bloodsucker, fame fucker

Bleedin' me dry like a goddamn vampire
#+end_quote

** [Bridge]
#+begin_quote
(Ah)

You said it was true love, but wouldn't that be hard?

You can't love anyone 'cause that would mean you had a heart

I tried to help you out, now I know that I can't

'Cause how you think's the kind of thing I'll never understand
#+end_quote

** [Chorus]

#+begin_quote
I've made some real big mistakes

But you make the worst one look fine

I should've known it was strange

You only come out at night

I used to think I was smart

But you made me look so naive

The way you sold me for parts

As you sunk your teeth into me, oh

Bloodsucker, fame fucker

Bleedin' me dry like a goddamn vampire
#+end_quote

* Instrumentation
** Vocals
** Guitar
* Production
** Producer
[[roam:Dan Nigro]]
* Personal Notes
