:PROPERTIES:
:ID:       23040329-bfd1-4a56-acf7-d5362a26bd1d
:mtime:    20240419042728 20240330001212
:ctime:    20240328233959
:END:
#+title: In the Middle - Dodie - You (2017)
#+filetags: :STUB:dodie:threesome:love:in_the_middle_dodie:you_dodie:

* Lyrics
 #+begin_quote
*Verse 1*

What are you doing Friday?

Wanna help my worlds collide? Let's make a bow with old cut ties

Do you want his number?

Or shall I be the one to call? I haven't seen him much at all

*Pre-Chorus 1*

It could be weird, but I think I'm into it

You know I'm one for the overly passionate

I like you, and I loved him

We could all be the best kind of friends

*Chorus 1*

You said you're into closure

Shake hands like you're supposed to

I'll be in the middle

While you two get along

You've got so much in common

Talk about your taste in women

I'll be in the middle

While you two get along

Hey!

*Verse 2*

Does he smile like I do?

Oh, it was shared, despite our flaws, I held his hand like I hold yours

Thanks for understanding

Oh, this could be a lot of fun, so break the awkward, come undone

*Pre-Chorus 1*

It could be weird, but I think I'm into it

You know I'm one for the overly passionate

I like you, and I loved him

We could all be the best kind of friends

*Chorus*

You said you're into closure

Shake hands like you're supposed to

I'll be in the middle

While you two get along

You've got so much in common

Talk about your taste in women

I'll be in the middle

While you two get along

*Bridge*

(In the middle, In the middle)

(I'll be in the middle, In the middle)

(I'll be in the middle, In the middle)

(In the middle)

Hey!

*Pre-Chorus 2*

It could be weird but I think I'm into it

You know I'm one for the overly passionate...

I said, it could be weird but I think I'm into it

You know I'm one for the overly passionate

I like you, and I loved him

We could all be the best kind of friends

*Chorus*

You said you're into closure

Shake hands like you're supposed to

I'll be in the middle

While you two get along

You've got so much in common

Talk about your taste in women

I'll be in the middle

While you two get along

*Outro*

I'll be in the middle, in the middle

Hey!
#+end_quote
* Instrumentation

* Production

* Personal Notes

